architecture:
  pe: 'wavelets'
  nn: 'siren'
  dim_hidden: 64
  num_layers: 2
embedding:
  max_scale: 3
  max_rotations: 75
  k_val: 6
  scale_factor: 1
  legendre: 10
  frequency_num: 16
  scale_shift: 1
  dilation_step: 6
data:
  num_samples: 5000
  meta_variable: 'LandSeaBinary'
  train_seed: 0
  valid_seed: 1
  num_classes: 1
  time_idx: 0
training:
  full: False
  lr: 0.0003
  wd: 0.001
  max_epochs: 300
  patience: 30
  batch_size: 2048
  dropout: False
regression: False
min_radius: 90
max_radius: 360
frequency_num: 64
dim_out: 1